// Re-export geometry utilities for backward compatibility
export {
  distance,
  midpoint,
  angle,
  normalizeAngle,
  pointOnLine,
  vectorFromAngle,
  addVector,
  snapToGrid,
  expandBounds,
  pointInBounds,
  boundsFromPoints,
  isPointNearLine,
  formatLength as formatDistance,
  formatArea,
  offsetToPosition,
  lineIntersection,
  lineFromPoints,
  lineFromPointAndAngle,
  distanceToInfiniteLine,
  createVector2D,
  type Line2D,
  type Vector2D
} from '@/types/geometry'
